#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wsgi_intercept
Version  : 0.10.3
Release  : 8
URL      : https://pypi.python.org/packages/source/w/wsgi_intercept/wsgi_intercept-0.10.3.tar.gz
Source0  : https://pypi.python.org/packages/source/w/wsgi_intercept/wsgi_intercept-0.10.3.tar.gz
Summary  : wsgi_intercept installs a WSGI application in place of a real URI for testing.
Group    : Development/Tools
License  : MIT
Requires: wsgi_intercept-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
python3-wsgi-intercept
======================
[![travis](https://secure.travis-ci.org/cdent/python3-wsgi-intercept.png)](https://secure.travis-ci.org/cdent/python3-wsgi-intercept)

%package python
Summary: python components for the wsgi_intercept package.
Group: Default

%description python
python components for the wsgi_intercept package.


%prep
%setup -q -n wsgi_intercept-0.10.3

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
