#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wsgi_intercept
Version  : 1.3.1
Release  : 18
URL      : http://pypi.debian.net/wsgi_intercept/wsgi_intercept-1.3.1.tar.gz
Source0  : http://pypi.debian.net/wsgi_intercept/wsgi_intercept-1.3.1.tar.gz
Summary  : wsgi_intercept installs a WSGI application in place of a real URI for testing.
Group    : Development/Tools
License  : MIT
Requires: wsgi_intercept-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
If you wish to run the tests without those tests which speak to
the internet (there are a few that validate that the intercept
does not intercept), set the WSGI_INTERCEPT_SKIP_NETWORK environment
variable to "True". Any other value or no value will mean that
the network tests will run.

%package python
Summary: python components for the wsgi_intercept package.
Group: Default

%description python
python components for the wsgi_intercept package.


%prep
%setup -q -n wsgi_intercept-1.3.1

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
